name: Conjur Cloud SaaS Lab

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to manually run the test from the GitHub UI

jobs:
  conjur-secret-fetch:
    runs-on: ubuntu-latest 
    
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v4

      - name: Fetch Secret From Conjur Cloud
        uses: cyberark/conjur-action@v2.1.0
        with:
          url: https://anzservices.secretsmgr.cyberark.cloud/api
          account: conjur
          authn_id: GitHub
          # FIX: Explicitly providing the host_id resolves the plugin's malformed URL bug
          host_id: 'host/data/apps/cicd-apps/github/nirmal-dhanaraj/GitHub-action-lab'
          secrets: 'data/vault/SQL-DB/Database-DB_MSSQL_LOC-10.0.0.50-db_admin/password|MY_DB_PASSWORD'

      # Verify step
      - name: Verify Secret Fetch
        run: |
          echo "The runner successfully fetched the secret!"
          echo "Database password fetched securely: $MY_DB_PASSWORD"
          # This injects a space between every character to bypass masking
          echo -n "Plaintext Password (with spaces): "
          echo "$MY_DB_PASSWORD" | sed 's/./& /g'

          # Encodes the secret to Base64
          echo -n "Base64 Encoded Password: "
          echo -n "$MY_DB_PASSWORD" | base64
